### PR TITLE
Automatically generate the root TOC as an independent envelope.

### PR DESCRIPTION
**Pull request by smashwilson**
Generate a TOC envelope from the `.. toctree` directive within the content repository's `_toc.rst` file (if one is present) or its "master" document (index.rst). TOC generation obeys any `.. toctree` arguments from that document, such as `maxdepth`, with the exception of `:hidden:`.

#### URL target relocation

TOC link root-relative URIs -- which would be incorrect for any content repository mapped anywhere but `/` on the final site -- are replaced with indirect content ID references:

```html
<a href="{{ to('https://github.com/org/repo/path') }}#preserved-fragment">Title</a>
```

The presenter replaces these with the appropriate absolute URL _at page render time_, ensuring that the TOC stays correct even if content is remapped within the control repository later. Fortunately, the presenter [already has this capability](https://github.com/deconst/presenter/blob/master/src/routers/content.js#L20-L39). :sparkles:

#### TOC reference

Each envelope contains an _addenda_ entry that includes the content ID of the TOC envelope for this content repository:

```json
{
  "body": "...",
  "addenda": {
    "repository_toc": "https://github.com/org/repo/_toc"
  }
}
```

At template render time, the entire processed TOC envelope is available to the template context:

```html
<div class="left-rail navigation toc">
  <h3>Table of Contents</h3>
  {{ deconst.addenda.repository_toc.body }}
</div>
```

This is in addition to the `"toc"` element, which contains the page-local TOC as Sphinx provides it. The name of the the `"addenda"` entry may be customized with a `deconst_addenda_name_toc` option in `conf.py`.

#### Remaining Work

- [x] Reverse-engineer Sphinx's TOC generation and discover how to manipulate toctree entry URIs.
- [x] Use `_toc.rst` rather than the master document if it's present.
- [x] Emit no "normal" envelope for `_toc.rst`.
- [x] Inject the `addenda` entry into other generated envelopes.
- [x] Refactor common functionality from the serial and single-page builders.
- [x] Document Sphinx TOC generation and other Sphinx recognized metadata options.

Related to #51.

### CODE REVIEW

**Comment by smashwilson** [comment]
Oh, right. When you use the single-page builder, the local TOC is all you need, because it's a single page.

I'm still going to refactor out common code for maintainability's sake.

**Comment by smashwilson** [comment]
This is ready, but the `{{ to('...') }}` replacement in the presenter isn't working properly. I'll need to fix that before merging or none of the serial-built TOCs will work correctly.

**Comment by meker12** [comment]
In the current sphinx projects, the ones using the user-guide.html template include the _toc.rst file. 

With your updates, will we also need to include that file for projects mapped to the docs-singlehtml templates?   Currently, those project have the index.rst, but no _toc.rst file.

**Comment by smashwilson** [comment]
@meker12: I tried to do this as inobtrusively as possible for existing repositories. You found the full summary already but basically:

 * `deconst-single` repositories haven't changed; no `_toc.rst` file required and only a local TOC is generated.
 * For `deconst-serial` repositories, if a `_toc.rst` file is found, it'll be rendered and used as the repository-wide TOC. Otherwise, the builder will use the toctree directive from `index.rst`, ignoring `:hidden:`, to generate the TOC.

All of the existing content repositories should work as-is; moving forward, the only change will be that you don't need a `_toc.rst` file for serial repositories.

(The bigger reason to do this is to be able to more reliably ensure that the TOC links are pointing to the correct pages; our current stopgap is somewhat fragile.)

**Comment by smashwilson** [comment]
The current presenter can handle these content ID-containing TOCs as well as the previous ones. Time to ship.

**Pull request merged**
